export const SET_STATUS = 'SET_STATUS';
export const SET_CHATS_HISTORY = 'SET_CHATS_HISTORY';
export const NEW_USER_CONNECTED = 'NEW_USER_CONNECTED';
export const SET_CHAT_HISTORY_STATUS = 'SET_CHAT_HISTORY_STATUS';
export const UPDATE_HISTORY = 'UPDATE_HISTORY';
