name: Deploy to Server

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-20.04
    timeout-minutes: 15  # Установка тайм-аута для джоба

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Add server to SSH known hosts
      run: |
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        echo "$(ssh-keyscan -t rsa 84.201.178.186)" >> ~/.ssh/known_hosts

    - name: Set up private key
      run: |
        echo "${{ secrets.SERVER_SSH_PRIVATE_KEY }}" > private_key
        chmod 600 private_key

    - name: Deploy to Server
      run: |
        ssh -i private_key -o StrictHostKeyChecking=no botkits@84.201.178.186 "cd /home/botkits/bot-kits-backend && git pull && sudo docker compose --file docker-compose-dev-release.yml down -v && sudo docker compose --file docker-compose-dev-release.yml up -d --build"
